spring:
  application:
    name: bank
  datasource:
    url: ${SQLITE_DATASOURCE_URL:jdbc:sqlite:./app/data/database.db}
    username: ${SQLITE_USER:sqlite}
    password: ${SQLITE_PASS:sqlite}
    driver-class-name: org.sqlite.JDBC
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  graphql:
    cors:
      allow-credentials: true
      max-age: 3600
      exposed-headers: '*'
      allowed-headers: '*'
      allowed-methods: '*'
      allowed-origins:
        - ${FRONT_SERVICE:http://localhost:4200}
      allowed-origin-patterns: /**

springdoc:
  swagger-ui:
    path: /v1/swagger-ui/index.html
  api-docs:
    path: /v1/swagger-ui/api-docs