spring:
  application:
    name: TM-EDUCATION-FACULTY-SERVICE
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${TM_EDU_KEY_CLOACK_SERVICE:http://backend.keycloak.auth:8080}/auth/realms/tm_education_security
  data:
    redis:
      host: ${TM_EDU_FACULTY_REDIS_HOST:localhost}
      port: ${TM_EDU_FACULTY_REDIS_PORT:6379}
      password: ${TM_EDU_FACULTY_REDIS_PASSWORD:admin}
      timeout: ${TM_EDU_FACULTY_REDIS_TIMEOUT:5000}

springdoc:
  swagger-ui:
    path: /v1/swagger-ui/index.html
  api-docs:
    path: /v1/swagger-ui/api-docs

server:
  port: 8081
eureka:
  instance:
    prefer-ip-address: true
  client:
    filter-only-up-instances: true
    service-url:
      defaultZone: ${TM_EDU_EUREKA_SERVICE:http://localhost:8761}/eureka/
