spring:
  application:
    name: bank
  graphql:
    cors:
      allow-credentials: true
      max-age: 3600
      exposed-headers: '*'
      allowed-headers: '*'
      allowed-methods: '*'
      allowed-origins:
        - http://localhost:4200
      allowed-origin-patterns: /**

springdoc:
  swagger-ui:
    path: /v1/swagger-ui/index.html
  api-docs:
    path: /v1/swagger-ui/api-docs