name: Push Docker hub

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on:
      ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SET up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build TMEDu Faculty service
        run: ./gradlew build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: docker buildx build -f . -t arzuv/tm-edu-faculty-service:${{ github.sha }} .

      - name: Push Docker image
        run: docker push arzuv/tm-edu-faculty-service:${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
